import { createFileRoute, Link } from "@tanstack/react-router";

import { LegalLayout } from "@/components/pm/legal-layout";

// Real Terms of Service page (SPEC-0012 R1/AC1), linked from signup instead
// of the previous inert "Terms and Privacy Policy" text. Public route --
// reachable before signing up.
export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service · PlaceMe" },
      {
        name: "description",
        content: "PlaceMe's Terms of Service for the beta pilot.",
      },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <LegalLayout title="Terms of Service">
      <p>
        These terms cover your use of PlaceMe's beta pilot: live voice group-discussion rooms with
        peers, and AI-generated feedback on your own sessions.
      </p>
      <div>
        <h2 className="text-base font-semibold text-foreground">Your account</h2>
        <p className="mt-2">
          You're responsible for the accuracy of the sign-up details you provide (name, college
          email, college, graduating year) and for keeping your password confidential. You can ask
          for your account to be deleted at any time from the "Privacy &amp; your data" section of
          your account.
        </p>
      </div>
      <div>
        <h2 className="text-base font-semibold text-foreground">Live sessions</h2>
        <p className="mt-2">
          Group-discussion rooms are live audio sessions with other students. Be respectful of the
          people you're practicing with -- abusive behavior can result in account suspension.
        </p>
      </div>
      <div>
        <h2 className="text-base font-semibold text-foreground">AI feedback</h2>
        <p className="mt-2">
          Feedback is generated by an AI model based on PlaceMe's current evaluation rubric. It's a
          practice aid, not a certification or guarantee of performance in any real placement
          process.
        </p>
      </div>
      <div>
        <h2 className="text-base font-semibold text-foreground">Data and privacy</h2>
        <p className="mt-2">
          What we collect, how long we keep it, and who can see it is covered in our{" "}
          <Link to="/privacy" className="font-semibold text-primary-glow">
            Privacy Policy
          </Link>
          .
        </p>
      </div>
      <div>
        <h2 className="text-base font-semibold text-foreground">Beta status</h2>
        <p className="mt-2">
          PlaceMe is in an early pilot. Features, these terms, and the Privacy Policy may change as
          the product and its legal review (SCRUM-24) progress; material changes will be reflected
          on this page.
        </p>
      </div>
    </LegalLayout>
  );
}
