/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as EndedRouteImport } from './routes/ended'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchRouteImport } from './routes/match'
import { Route as SessionRouteImport } from './routes/session'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppJoinRouteImport } from './routes/app.join'
import { Route as AppNewRouteImport } from './routes/app.new'
import { Route as RoomsNewRouteImport } from './routes/rooms.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const EndedRoute = EndedRouteImport.update({
  id: '/ended',
  path: '/ended',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJoinRoute = AppJoinRouteImport.update({
  id: '/app/join',
  path: '/app/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/app/new',
  path: '/app/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsNewRoute = RoomsNewRouteImport.update({
  id: '/rooms/new',
  path: '/rooms/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/consent': typeof ConsentRoute
  '/ended': typeof EndedRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/session': typeof SessionRoute
  '/signup': typeof SignupRoute
  '/app/join': typeof AppJoinRoute
  '/app/new': typeof AppNewRoute
  '/rooms/new': typeof RoomsNewRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/consent': typeof ConsentRoute
  '/ended': typeof EndedRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/session': typeof SessionRoute
  '/signup': typeof SignupRoute
  '/app/join': typeof AppJoinRoute
  '/app/new': typeof AppNewRoute
  '/rooms/new': typeof RoomsNewRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/consent': typeof ConsentRoute
  '/ended': typeof EndedRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/session': typeof SessionRoute
  '/signup': typeof SignupRoute
  '/app/join': typeof AppJoinRoute
  '/app/new': typeof AppNewRoute
  '/rooms/new': typeof RoomsNewRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/consent'
    | '/ended'
    | '/history'
    | '/join'
    | '/lobby'
    | '/login'
    | '/match'
    | '/session'
    | '/signup'
    | '/app/join'
    | '/app/new'
    | '/rooms/new'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/consent'
    | '/ended'
    | '/history'
    | '/join'
    | '/lobby'
    | '/login'
    | '/match'
    | '/session'
    | '/signup'
    | '/app/join'
    | '/app/new'
    | '/rooms/new'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/consent'
    | '/ended'
    | '/history'
    | '/join'
    | '/lobby'
    | '/login'
    | '/match'
    | '/session'
    | '/signup'
    | '/app/join'
    | '/app/new'
    | '/rooms/new'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ConsentRoute: typeof ConsentRoute
  EndedRoute: typeof EndedRoute
  HistoryRoute: typeof HistoryRoute
  JoinRoute: typeof JoinRoute
  LobbyRoute: typeof LobbyRoute
  LoginRoute: typeof LoginRoute
  MatchRoute: typeof MatchRoute
  SessionRoute: typeof SessionRoute
  SignupRoute: typeof SignupRoute
  AppJoinRoute: typeof AppJoinRoute
  AppNewRoute: typeof AppNewRoute
  RoomsNewRoute: typeof RoomsNewRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ended': {
      id: '/ended'
      path: '/ended'
      fullPath: '/ended'
      preLoaderRoute: typeof EndedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/join': {
      id: '/app/join'
      path: '/app/join'
      fullPath: '/app/join'
      preLoaderRoute: typeof AppJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/new': {
      id: '/app/new'
      path: '/app/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/new': {
      id: '/rooms/new'
      path: '/rooms/new'
      fullPath: '/rooms/new'
      preLoaderRoute: typeof RoomsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ConsentRoute: ConsentRoute,
  EndedRoute: EndedRoute,
  HistoryRoute: HistoryRoute,
  JoinRoute: JoinRoute,
  LobbyRoute: LobbyRoute,
  LoginRoute: LoginRoute,
  MatchRoute: MatchRoute,
  SessionRoute: SessionRoute,
  SignupRoute: SignupRoute,
  AppJoinRoute: AppJoinRoute,
  AppNewRoute: AppNewRoute,
  RoomsNewRoute: RoomsNewRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
